# Generated by Django 3.2.9 on 2021-12-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
