# Generated by Django 3.2.9 on 2021-12-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delete',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
