# Generated by Django 3.2.9 on 2021-12-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
