# Generated by Django 3.2.9 on 2021-12-06 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='delete',
            new_name='delet',
        ),
    ]
