# Generated by Django 3.2.9 on 2021-12-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_delete_item_delet'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='delet',
            field=models.BooleanField(default=False),
        ),
    ]
