# Generated by Django 3.2.9 on 2021-12-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_todolist_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='avatar',
        ),
        migrations.AddField(
            model_name='todolist',
            name='sex',
            field=models.BooleanField(default=False),
        ),
    ]
