# Generated by Django 3.2.9 on 2021-12-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211212_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='sex',
        ),
    ]
